### ISSUE TITLE
Accessing array items in the object index

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/java-interpreter#19] opened 2019-03-22 12:22 UTC
There seems to be a problem when accessing items inside arrays in the object index. 

For example, this:
```
_test=[[a;b]];
letters1=%test>0>0
```
=>
```
{
    "letters1": "a"
}
```

Should return the same as this:

```
?=[[a;b]];
letters2=%0>0>0
```
But it doesn't =>
```
{
    "letters2": [
        "a",
        "b"
    ]
}
```

**Comment by alexdalitz** [comment] 2019-03-27 10:42
This is now fixed (but not yet committed)

**Comment by alexdalitz** [comment] 2019-04-08 08:22
Tony and I spoke about this last week. We both think it is very strange behaviour, and out of keeping with the rest of the language.

The problem is that the object index example is ambiguous - do we have an object reference of size one, which is the array `[[a;b]]` or do we have an object index which is defined as an array, the first element of which is `[a;b]`?

To fit in with the rest of the language, and to stop the tests looking insane, we thought that the answer was that it should be treated as the latter - in which case the expression `letters2=%0>0>0` does not make sense, and will raise an error.

Very happy to discuss this more!

Thanks,


Alex.

**Comment by elliottinvent** [comment] 2019-04-08 09:00
Yes, I think this is sensible. I think the issue was more about the bizarre return output of the second example so if that's raising an error then that makes sense. 

I'm guessing that for the second case to work (first value of object index is an array), then it'd need to be:

```
?=[[[a;b]]];
letters2=%0>0>0
```

->

```
{
    "letters1": "a"
}
```

If that's correct and the test above works then please close the issue.

**Closed** 2019-04-12 17:54 UTC
